spring:
  application:
    name: ministore-admin-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.mini.store.127.0.0.1.nip.io/realms/ministore
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak.mini.store.127.0.0.1.nip.io/realms/ministore
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service-k8s
            client-secret: 667HXYv9aJloOwmdpbJQqIFPfLMCF5C4
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service-k8s
            client-secret: 667HXYv9aJloOwmdpbJQqIFPfLMCF5C4
          discovery:
            provider: keycloak
            client-id: admin-service-k8s
            client-secret: 667HXYv9aJloOwmdpbJQqIFPfLMCF5C4
            authorization-grant-type: client_credentials
            scope:
              - discovery
server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
eureka:
  client:
    enabled: false