apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-vmagent-cm
data:
  promscrape.yaml: |
    scrape_configs:
      - job_name: ministore_config_server
        static_configs:
          - targets: ["http://localhost:8888"]
            labels:
              application: ministore-config-server
        metrics_path: /actuator/prometheus
        oauth2:
          client_id: victoria-metrics
          client_secret: OLOTeDyuXdXPdUafgt7UUAxiMMLPuiU1
          token_url: http://keycloak.mini.store.127.0.0.1.nip.io/realms/ministore/protocol/openid-connect/token
          scopes:
            - metrics
          endpoint_params:
            grant_type: client_credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ministore-config-server
  namespace: ministore
  labels:
    app: ministore-config-server
spec:
  selector:
    matchLabels:
      app: ministore-config-server
  template:
    metadata:
      labels:
        app: ministore-config-server
    spec:
      volumes:
        - name: vmconfig
          configMap:
            name: config-server-vmagent-cm
      containers:
        - name: ministore-config-server
          image: 192.168.49.1:5000/ministore/config-server:0.0.1
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: git,k8s
            - name: LOKI
              value: http://loki-svc.selmag.svc.cluster.local:3100
        - name: vmagent
          image: victoriametrics/vmagent:v1.93.12
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - -promscrape.config=/etc/opt/vmagent/promscrape.yaml
            - -remoteWrite.url=http://vm-svc.ministore.svc.cluster.local:8428/api/v1/write
            - -remoteWrite.label=instance=$(NODE_NAME)
          volumeMounts:
            - mountPath: /etc/opt/vmagent
              name: vmconfig
---
apiVersion: v1
kind: Service
metadata:
  name: ministore-config-server-svc
  namespace: ministore
spec:
  type: NodePort
  ports:
    - port: 8888
      name: http
  selector:
    app: ministore-config-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ministore-config-server-ingress
  namespace: ministore
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: config.mini.store.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ministore-config-server-svc
                port:
                  name: http
