apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-vmagent-cm
data:
  promscrape.yaml: |
    scrape_configs:
      - job_name: ministore_eureka_server
        static_configs:
          - targets: ["http://localhost:8761"]
            labels:
              application: ministore-eureka-server
        metrics_path: /actuator/prometheus
        oauth2:
          client_id: victoria-metrics
          client_secret: OLOTeDyuXdXPdUafgt7UUAxiMMLPuiU1
          token_url: http://keycloak.mini.store.127.0.0.1.nip.io/realms/ministore/protocol/openid-connect/token
          scopes:
            - metrics
          endpoint_params:
            grant_type: client_credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ministore-eureka-server-deployment
  labels:
    app: ministore-eureka-server
spec:
  selector:
    matchLabels:
      app: ministore-eureka-server
  template:
    metadata:
      labels:
        app: ministore-eureka-server
    spec:
      volumes:
        - name: vmconfig
          configMap:
            name: eureka-vmagent-cm
      hostAliases:
        - ip: "192.168.49.2"
          hostnames:
            - "keycloak.mini.store.127.0.0.1.nip.io"
      containers:
        - name: ministore-eureka-server
          image: 192.168.49.1:5000/ministore/eureka-server:0.0.1
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloudconfig,k8s
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config:config-password@ministore-config-server-svc.ministore.svc.cluster.local:8888
            - name: LOKI
              value: http://loki-svc.ministore.svc.cluster.local:3100
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
        - name: vmagent
          image: victoriametrics/vmagent:v1.93.12
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - -promscrape.config=/etc/opt/vmagent/promscrape.yaml
            - -remoteWrite.url=http://vm-svc.ministore.svc.cluster.local:8428/api/v1/write
            - -remoteWrite.label=instance=$(NODE_NAME)
          volumeMounts:
            - mountPath: /etc/opt/vmagent
              name: vmconfig
---
apiVersion: v1
kind: Service
metadata:
  name: ministore-eureka-server-svc
  namespace: ministore
spec:
  type: NodePort
  ports:
    - port: 8761
      name: http
  selector:
    app: ministore-eureka-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ministore-eureka-server-ingress
spec:
  rules:
    - host: eureka.mini.store.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ministore-eureka-server-svc
                port:
                  name: http