spring:
  application:
    name: ministore-api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: catalogue-service-route
              uri: lb://ministore-catalogue-service
              predicates:
                - Host=**catalogue.api.mini.store.127.0.0.1.nip.io**
            - id: feedback-service-route
              uri: lb://ministore-feedback-service
              predicates:
                - Host=**feedback.api.mini.store.127.0.0.1.nip.io**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://host.docker.internal:8082/realms/ministore
        registration:
          discovery:
            provider: keycloak
            client-id: api-gateway
            client-secret: fslnapf076wzg2r4MMYiRdEAyKsHYWQG
            authorization-grant-type: client_credentials
            scope:
              - discovery
server:
  port: 8086
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
    register-with-eureka: false
    registry-fetch-interval-seconds: 1
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1