spring:
  application:
    name: catalogue-service

  security:
    user:
      name: catalogue_service_user
      password: password
      roles:
        - SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5433/catalogue
    username: postgres
    password: postgres
  flyway:
    schemas:
      - public
      - catalogue

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/ministore

server:
  port: 8081

logging:
  level:
    sql: info
