spring:
  application:
    name: ministore-catalogue-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@host.docker.internal:8888
server:
  port: 8081
  forward-headers-strategy: native
