spring:
  application:
    name: ministore-eureka-server
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@localhost:8888

server:
  port: 8761
