apiVersion: v1
kind: ConfigMap
metadata:
  name: feedback-vmagent-cm
data:
  promscrape.yml: |
    scrape_configs:
      - job_name: ministore_feedback_service
        static_configs:
          - targets: ["http://localhost:8080"]
            labels:
              application: ministore-feedback-service
        metrics_path: /actuator/prometheus
        oauth2:
          client_id: victoria-metrics
          client_secret: OLOTeDyuXdXPdUafgt7UUAxiMMLPuiU1
          token_url: http://keycloak.mini.store.127.0.0.1.nip.io/realms/ministore/protocol/openid-connect/token
          scopes:
            - metrics
          endpoint_params:
            grant_type: client_credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ministore-feedback-service-deployment
  labels:
    app: ministore-feedback-service
spec:
  selector:
    matchLabels:
      app: ministore-feedback-service
  template:
    metadata:
      labels:
        app: ministore-feedback-service
    spec:
      volumes:
        - name: vmconfig
          configMap:
            name: feedback-vmagent-cm
      hostAliases:
        - ip: "192.168.49.2"
          hostnames:
            - "keycloak.mini.store.127.0.0.1.nip.io"
      containers:
        - name: ministore-feedback-service
          image: 192.168.49.1:5000/ministore/feedback-service:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: LOKI
              value: http://loki-svc.ministore.svc.cluster.local:3100
        - name: vmagent
          image: victoriametrics/vmagent:v1.93.12
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - -promscrape.config=/etc/opt/vmagent/promscrape.yml
            - -remoteWrite.url=http://vm-svc.ministore.svc.cluster.local:8428/api/v1/write
            - -remoteWrite.label=instance=$(NODE_NAME)
          volumeMounts:
            - mountPath: /etc/opt/vmagent
              name: vmconfig
---
apiVersion: v1
kind: Service
metadata:
  name: ministore-feedback-service-svc
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
  selector:
    app: ministore-feedback-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ministore-feedback-service-ingress
spec:
  rules:
    - host: feedback.api.mini.store.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ministore-feedback-service-svc
                port:
                  name: http