spring:
  application:
    name: ministore-feedback-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@host.docker.internal:8888

server:
  port: 8084
  forward-headers-strategy: framework
