spring:
  application:
    name: ministore-feedback-service
  boot:
    admin:
      client:
        enabled: false

  data:
    mongodb:
      uri: mongodb://feedback-db-svc.ministore.svc.cluster.local:27017/feedback

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.mini.store.127.0.0.1.nip.io/realms/ministore
      client:
        registration:
          keycloak:
            client-secret: yqMrfwoGO8Vl4BvytbJb4Xi2i0wez9hs
            client-id: feedback-service
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-secret: yqMrfwoGO8Vl4BvytbJb4Xi2i0wez9hs
            client-id: feedback-service
            authorization-grant-type: client_credentials
            scope:
              - discovery
        provider:
          keycloak:
            issuer-uri: http://keycloak.mini.store.127.0.0.1.nip.io/realms/ministore

server:
  forward-headers-strategy: framework
  port: 8080

springdoc:
  swagger-ui:
    oauth:
      client-id: feedback-service-swagger-ui
      use-pkce-with-authorization-code-grant: true

keycloak:
  uri: http://keycloak.mini.store.127.0.0.1.nip.io

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

  zipkin:
    tracing:
      endpoint: http://tempo-svc.ministore.svc.cluster.local:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    enabled: false
