spring:
  application:
    name: ministore-customer-app
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@host.docker.internal:8888

server:
  port: 8083
  forward-headers-strategy: native
