spring:
  application:
    name: customer-app
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: customer-app
          service-host-type: ip
        url: http://localhost:8085

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/ministore
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: WuiVi5VBs98DTmN3BEbGiLX40SwOGpdH
            scope:
              - openid
              - view_catalogue
          metrics:
            provider: keycloak
            client-secret: SQBeQbPyvr0IQ3oNsegWKauQITWWub0n
            client-id: customer-app-metrics-client
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/ministore

server:
  port: 8083

ministore:
  services:
    catalogue:
      uri: http://localhost:8081
    feedback:
      uri: http://localhost:8084

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"